### ISSUE TITLE
Compiler error for Utils.swift against curr.threadDictionary

### ISSUE THREAD

**Issue by kechan** [jph00/BaseMath#5] opened 2019-01-15 22:45 UTC
```
extension Thread {
  static func setToTLS<T>(_ value: T, _ key: String)->T {
    let curr = Thread.current
    var dict = curr.threadDictionary
    dict[key] = value
    curr.threadDictionary = dict  <------- **Cannot assign to property: 'threadDictionary' is a get-only property**
    return value
  }
}
```

Compiling with swift 4.2.1 on Mac OS X 10.13.6. I tried this with both "swift build..." and also as a project in Xcode.

**Comment by kechan** [comment] 2019-01-15 22:47
Would this
`
curr.threadDictionary[key] = value
`
do? This compiled.

**Comment by kechan** [comment] 2019-01-17 22:04
Here is the full error:

$ swift build
Compile CBaseMath CBaseMath.cpp
Compile CBaseMath CDistribution.cpp
Compile Swift Module 'BaseMath' (7 sources)
/Users/kelvinchan/Documents/BaseMath/Sources/BaseMath/Utils.swift:21:27: error: cannot assign to property: 'threadDictionary' is a get-only property
    curr.threadDictionary = dict
    ~~~~~~~~~~~~~~~~~~~~~ ^
error: terminated(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/kelvinchan/Documents/BaseMath/.build/debug.yaml main output:

trying:
curr.threadDictionary[key] = value

**Comment by kechan** [comment] 2019-01-18 22:46
Note: curr.threadDictionary is not a Swift Dictionary. Checking up on apple doc, it is a NSMutableDictionary. This means it is a reference type, so the above "fix" should assign they key/value expectedly. However, since I aint clear what this code does, I haven't tested this in the context of this library.

**Comment by jph00** [comment] 2019-01-19 14:38
Ah OK - this is a problem in Swift 4.2 Linux. Looks like it will be fixed in Swift 5.0. I'll close this now, and fix it once 5.0 is out.

**Closed by jph00** 2019-01-19 14:38 UTC

**Comment by kechan** [comment] 2019-01-21 03:20
Should we leave this issue open since Xcode/Mac is currently on Swift 4.2? This is to let others know more conveniently what's going on and what to workaround.

**Comment by kechan** [comment] 2019-01-21 08:05
@algal 
Yes. I pointed this out earlier the reasons are in Swift 4.2:

1) Thread.current.threadDictionary is a read-only property.
2) threadDictionary is not a Swift Dictionary but a NSMutableDictionary, thus the workaround is actually the right way doing this in 4.2. 

Having said that, I am not aware of the roadmap for Swift 5.0, which Jeremy alluded to. It is possible even this stops working should they decide to make threadDictionary a true Swift Dictionary. Apple has habit of "upgrading" certain properties moving away from Objective C (those NS****) stuff, to purer swift. 

We will have to watch out.

**Comment by algal** [comment] 2019-01-23 07:34
Yes, sorry, `gyb` is what I meant. (Autocorrect.) The problem is that I am trying to build on Linux not in a full Linux VM but just on a docker image. I've found this a pretty good workflow for cross-platform Swift dev in the past (https://github.com/algal/SwiftOnLambda). But Apple's `swift:4.2` image is  not equipped with `gyb` or `pip`. Even after apt-get installing pip and then installing `gyb`, there are still some missing pieces of c++ tooling. I'll see if I can find or build a more fatter image.
